#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = ui

SOURCES *= \
    ./chartable.cpp \
    ./handwritecore.cpp \
    ./main.cpp \
    ./topui.cpp

HEADERS *= \
    ./chartable.h \
    ./handwritecore.h \
    ./topui.h

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
